// AUTO-GENERATED by scripts/generate-agenda-image-manifest.mjs
// Add images to the container-images/detail-images folders and run dev/build.

export type AgendaActivityImage = {
  path: string;
  fileName: string;
  label: string;
};

export const agendaContainerImages: AgendaActivityImage[] = [
  { path: "/images/agenda/activities/container-images/boottocht.png", fileName: "boottocht.png", label: "Boottocht" },
  { path: "/images/agenda/activities/container-images/bowlen.png", fileName: "bowlen.png", label: "Bowlen" },
  { path: "/images/agenda/activities/container-images/karten.png", fileName: "karten.png", label: "Karten" },
  { path: "/images/agenda/activities/container-images/kerst.png", fileName: "kerst.png", label: "Kerst" },
  { path: "/images/agenda/activities/container-images/lasergamen.png", fileName: "lasergamen.png", label: "Lasergamen" },
  { path: "/images/agenda/activities/container-images/nieuwjaar.png", fileName: "nieuwjaar.png", label: "Nieuwjaar" },
  { path: "/images/agenda/activities/container-images/pasen.png", fileName: "pasen.png", label: "Pasen" },
  { path: "/images/agenda/activities/container-images/picknick.png", fileName: "picknick.png", label: "Picknick" },
  { path: "/images/agenda/activities/container-images/poolen.png", fileName: "poolen.png", label: "Poolen" },
  { path: "/images/agenda/activities/container-images/schilderen.png", fileName: "schilderen.png", label: "Schilderen" }
];

export const agendaDetailImages: AgendaActivityImage[] = [];
